### ISSUE TITLE
out is getting wrong.. everytime is says OK

### ISSUE THREAD

**Issue by afrozkh** [JeanMarieAries/check-netapp-volume#3]
[root@test ~]# /opt/nagios/libexec/check_netapp-2.7.py -H xxxxxxxx -U user -P pass -I vol0100 -W 1 -C 1
OK

**Comment by JeanMarieAries** [comment]
Hi, Could you comment the line 123, run the script, and give me back the tmp file generated in $filedir ? Thanks you.

**Comment by afrozkh** [comment]
Hi,

Please ignore.. it is working now. got some mistake in command syntax and thanks for your quick response.
